version: '3'

services:
  uniblog:
    image: ccr.ccs.tencentyun.com/tcb-100013435734-trdg/uni-blog:latest
    environment:
      DATABASE_URL: postgres://postgres:root_password@postgres:5432/uni_blog
      AUTH_SECRET: P1oigOtITzC7WICj+G6L1JN1u3EyrErLRnq0pxPyiJE=
    volumes:
      - ./volumes/static:/app/_uni
    depends_on:
      - postgres
    restart: always
    ports:
      - '3000:3000'

  caddy:
    image: caddy
    ports:
      - '80:80'
      - '443:443'
    environment:
      EMAIL: uniblog@example.com
      DOMAIN: example.com
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./volumes/static:/app/_uni
      - ./volumes/caddy/data:/data
      - ./volumes/caddy/config:/config
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: uni_blog
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    restart: always # 设置容器自动重启

